In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [63]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Datasets/Salary Data.csv')


In [17]:
df

Age  Gender  Education Level  Job Title Years of Experience    Salary
0    32.0       1                0        159                 5.0   90000.0
1    28.0       0                1         17                 3.0   65000.0
2    45.0       1                2        130                15.0  150000.0
3    36.0       0                0        101                 7.0   60000.0
4    52.0       1                1         22                20.0  200000.0
..    ...     ...              ...        ...                 ...       ...
370  35.0       0                0        131                 8.0   85000.0
371  43.0       1                1         30                19.0  170000.0
372  29.0       0                0         70                 2.0   40000.0
373  34.0       1                0        137                 7.0   90000.0
374  44.0       0                2        110                15.0  150000.0

[375 rows x 6 columns]

In [64]:
df.info

<bound method DataFrame.info of       Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]>

In [65]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [66]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df["Years of Experience"] = df["Years of Experience"].fillna(df['Years of Experience'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())


In [67]:
most_frequent_category=df['Gender'].mode().iloc[0]
df['Gender'].fillna(most_frequent_category,inplace=True)

most_frequent_category=df['Job Title'].mode().iloc[0]
df['Job Title'].fillna(most_frequent_category,inplace=True)

most_frequent_category=df['Education Level'].mode().iloc[0]
df['Education Level'].fillna(most_frequent_category,inplace=True)



In [68]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [69]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()


In [70]:
df['Gender'] = le.fit_transform(df['Gender'])
df['Education Level'] = le.fit_transform(df['Education Level'])
df['Job Title'] = le.fit_transform(df['Job Title'])

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  375 non-null    float64
 1   Gender               375 non-null    int64  
 2   Education Level      375 non-null    int64  
 3   Job Title            375 non-null    int64  
 4   Years of Experience  375 non-null    float64
 5   Salary               375 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 17.7 KB


In [72]:
X=df.drop(columns=['Salary'])
y=df['Salary']

In [ ]:
X

In [ ]:
y

K fold cross validation

```
# This is formatted as code
```



In [76]:
from sklearn.tree import DecisionTreeRegressor

DTregressor = DecisionTreeRegressor(criterion='squared_error',  # Mean Squared Error
                                    max_depth=10,  # Maximum depth of the tree
                                    min_samples_split=2,  # Minimum number of samples required to split an internal node
                                    min_samples_leaf=1,  # Minimum number of samples required to be at a leaf node
                                    max_features=None,  # Number of features to consider when looking for the best split
                                    max_leaf_nodes=None,  # Maximum number of leaf nodes
                                    min_impurity_decrease=0.0)  # A node will be split if this split induces a decrease of the impurity greater than or equal to this value


In [80]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

K_fold = KFold(10)  # Fix the variable name here

result1 = cross_val_score(DTregressor, X, y, cv=K_fold, scoring='neg_mean_squared_error')
result2 = cross_val_score(DTregressor, X, y, cv=K_fold, scoring='neg_mean_absolute_percentage_error')
result3 = cross_val_score(DTregressor, X, y, cv=K_fold, scoring='r2')


In [81]:
result1 #negative MSE

array([-7.87016859e+08, -8.78513162e+08, -5.05352694e+08, -2.85620681e+08,
       -1.56145212e+08, -1.55920044e+08, -1.25146037e+08, -5.18561639e+07,
       -8.94209769e+07, -3.36560094e+08])

In [82]:
result2   #negative MSE

array([-0.19877762, -0.17486017, -0.1658726 , -0.12439836, -0.12226645,
       -0.11160742, -2.77469427, -0.04877951, -0.05432777, -0.06268824])

In [83]:
result3

array([0.75774272, 0.64775764, 0.87073818, 0.85687248, 0.92324191,
       0.92861107, 0.94478901, 0.97147089, 0.95619725, 0.89191767])

In [84]:
overall_MAE_percentage= sum(result2)/len(result2)